"""add user to project

Revision ID: 04fb373ac6db
Revises: 169e43028a60
Create Date: 2026-10-08 23:38:52.455032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fb373ac6db'
down_revision: Union[str, Sequence[str], None] = '169e43028a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_foreign_key('fk_project_user_id_users', 'project', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_project_user_id_users', 'project', type_='foreignkey')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
